# -*- coding: utf-8 -*-
"""W_MoE_GL_RL_Inference_Memory_ECE_Brier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1awApFAZtw0OAB0_ZgJRiN9she2xeqYjk

# W_MoE_GL_RL_Inference_Memory
"""

import torch
import pandas as pd
import json
import torch.nn as nn
import torch.nn.functional as F
from sklearn.feature_extraction.text import TfidfVectorizer
from safetensors.torch import load_file
import numpy as np
import os

# Define paths for different expert datasets and models
expert_configs = {
    "alpaca": {
        "adapter_weights": "/kaggle/input/worksapce/orkspace/LLaMa-2-7B-Alpaca/results/alpaca_adapter/adapter_model.safetensors",
        "gamma": "/kaggle/input/worksapce/orkspace/LLaMa-2-7B-Alpaca/results/alpaca_adapter/adapter_config.json",
        "base_weights": "/kaggle/input/worksapce/orkspace/LLaMa-2-7B-Alpaca/base_model_weights.pth",
        "train_data": "/kaggle/input/worksapce/orkspace/Dataset/Alpaca/Alpaca_Train.json",
        "test_data": "/kaggle/input/worksapce/orkspace/Dataset/Alpaca/Alpaca_Test.json"
    },
    "beavertails": {
        "adapter_weights": "/kaggle/input/worksapce/orkspace/LLaMa-2-7B-BeaverTails/results/beavertails_adapter/adapter_model.safetensors",
        "gamma": "/kaggle/input/worksapce/orkspace/LLaMa-2-7B-BeaverTails/results/beavertails_adapter/adapter_config.json",
        "base_weights": "/kaggle/input/worksapce/orkspace/LLaMa-2-7B-BeaverTails/base_model_weights.pth",
        "train_data": "/kaggle/input/worksapce/orkspace/Dataset/BeaverTails/BeaverTails_Train.csv",
        "test_data": "/kaggle/input/worksapce/orkspace/Dataset/BeaverTails/BeaverTails_Test.csv"
    },
    "truthfulqa": {
        "adapter_weights": "/kaggle/input/worksapce/orkspace/LLaMa-2-7b-TruthfulQA/results/truthfulqa_adapter/adapter_model.safetensors",
        "gamma": "/kaggle/input/worksapce/orkspace/LLaMa-2-7b-TruthfulQA/results/truthfulqa_adapter/adapter_config.json",
        "base_weights": "/kaggle/input/worksapce/orkspace/LLaMa-2-7b-TruthfulQA/base_model_weights.pth",
        "train_data": "/kaggle/input/worksapce/orkspace/Dataset/TruthfulQA/TruthfulQA_Train.csv",
    "test_data":  "/kaggle/input/worksapce/orkspace/Dataset/TruthfulQA/TruthfulQA_Test.csv"
    }
}

# Define Feed Forward Network (FFN) for each expert
class ExpertFFN(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(ExpertFFN, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, output_dim)
        self.activation = nn.ReLU()

    def forward(self, x):
        x = self.activation(self.fc1(x))
        return self.fc2(x)

# Initialize TF-IDF vectorizer
vectorizer = TfidfVectorizer(max_features=500)

def text_to_numeric(text_series):
    """Convert text data into TF-IDF numerical vectors."""
    return vectorizer.fit_transform(text_series).toarray()

# Function to load dataset and ensure text is converted to numerical values
def load_data(expert_name):
    paths = expert_configs[expert_name]
    if paths["train_data"].endswith(".json"):
        train_data = pd.read_json(paths["train_data"])
        test_data = pd.read_json(paths["test_data"])
    else:
        train_data = pd.read_csv(paths["train_data"])
        test_data = pd.read_csv(paths["test_data"])
    text_columns = train_data.select_dtypes(include=['object']).columns
    if not text_columns.empty:
        train_data = pd.DataFrame(text_to_numeric(train_data[text_columns[0]]))
        test_data = pd.DataFrame(text_to_numeric(test_data[text_columns[0]]))
    train_data = train_data.select_dtypes(include=['number'])
    test_data = test_data.select_dtypes(include=['number'])
    return train_data, test_data

# Load all experts and initialize FFN models
experts = {}
for name in expert_configs.keys():
    train_data, test_data = load_data(name)
    input_dim = train_data.shape[1] if train_data.shape[1] > 0 else 1
    experts[name] = {
        "ffn": ExpertFFN(input_dim=input_dim, hidden_dim=128, output_dim=64),
        "train_data": train_data,
        "test_data": test_data
    }

# Temperature-scaled softmax for gating
def temperature_scaled_softmax(gamma_values, temperature=0.7):
    gamma_tensor = torch.tensor(list(gamma_values.values()), dtype=torch.float32)
    scaled_softmax = F.softmax(gamma_tensor / temperature, dim=0)
    return {k: v.item() for k, v in zip(gamma_values.keys(), scaled_softmax)}

# Entropy regularizer
def entropy_regularization(probabilities):
    return -torch.sum(probabilities * torch.log(probabilities + 1e-8))

# KL divergence penalty
def kl_divergence(p, q, epsilon=1e-8):
    p = torch.clamp(p, min=epsilon)
    q = torch.clamp(q, min=epsilon)
    return torch.sum(p * torch.log(p / q))

# Update gamma based on losses
def update_gamma_values(gamma_values, expert_losses, scaling_factor=0.1):
    updated = {}
    total_loss = sum(expert_losses.values())
    for expert, loss in expert_losses.items():
        updated[expert] = gamma_values[expert] * (total_loss / (loss + 1e-8)) * scaling_factor
    s = sum(updated.values())
    return {k: v/s for k, v in updated.items()}

# Router class to manage expert selection using MoCaE + Gating Loss + Regularization Loss (RL)
class MoCaERouterWithPenalties(nn.Module):
    def __init__(self, expert_ffns, gamma_values, previous_gamma_values=None, temperature=0.7):
        super().__init__()
        self.expert_ffns = expert_ffns
        self.gamma_values = gamma_values
        self.previous_gamma_values = previous_gamma_values or gamma_values
        self.temperature = temperature

    def forward(self, x):
        # 1. Temperature-scaled gating
        gamma_scaled = temperature_scaled_softmax(self.gamma_values, self.temperature)

        # 2. Compute weighted expert outputs
        expert_outputs = {
            expert: ffn(x) * gamma_scaled[expert]
            for expert, ffn in self.expert_ffns.items()
        }
        weighted_sum = sum(expert_outputs.values())

        # 3. Entropy regularization
        entropy_reg = entropy_regularization(
            torch.tensor(list(gamma_scaled.values()), dtype=torch.float32)
        )

        # 4. KL divergence penalty to prevent sharp gamma jumps
        kl_penalty = kl_divergence(
            torch.tensor(list(gamma_scaled.values()), dtype=torch.float32),
            torch.tensor(list(self.previous_gamma_values.values()), dtype=torch.float32)
        )

        # 5. Gating loss: KL(gamma_scaled || uniform)
        num_experts = len(gamma_scaled)
        uniform = torch.full((num_experts,), 1.0 / num_experts)
        gating_loss = kl_divergence(
            torch.tensor(list(gamma_scaled.values()), dtype=torch.float32),
            uniform
        )

        # 6. Regularization loss (RL): KL(gamma_scaled || gamma_prior)
        gamma_prior = torch.full((num_experts,), 1.0 / num_experts)  # assuming uniform prior
        rl_loss = kl_divergence(
            torch.tensor(list(gamma_scaled.values()), dtype=torch.float32),
            gamma_prior
        )

        # 7. Update previous gammas
        self.previous_gamma_values = self.gamma_values

        # 8. Total loss
        total_loss = (
            torch.mean(weighted_sum)
            + 0.1 * entropy_reg
            + 0.01 * kl_penalty
            + 0.05 * gating_loss
            + 0.05 * rl_loss  # Added RL loss here
        )

        # 9. Update gamma values based on expert performance
        expert_losses = {expert: total_loss.item() for expert in self.expert_ffns.keys()}
        self.gamma_values = update_gamma_values(self.gamma_values, expert_losses)

        return total_loss, weighted_sum, entropy_reg, kl_penalty

# Process input through router
def process_input_data_with_penalties():
    for expert, vals in experts.items():
        data = vals["train_data"]
        if data.empty:
            print(f"Skipping {expert}: No numeric data found!")
            continue
        tensor = torch.tensor(data.values, dtype=torch.float32)
        total_loss, weighted_sum, entropy_reg, kl_pen = router_with_penalties(tensor)
        print(f"Processed {expert} - Loss:{total_loss.item()} Entropy:{entropy_reg.item()} KL:{kl_pen.item()}")

# Save aggregated embeddings
def save_aggregated_output_embeddings():
    aggregated = {}
    for expert, vals in experts.items():
        data = vals["train_data"]
        if data.empty:
            print(f"Skipping {expert}: No numeric data!")
            continue
        tensor = torch.tensor(data.values, dtype=torch.float32)
        _, weighted_sum, _, _ = router_with_penalties(tensor)
        aggregated[expert] = weighted_sum.detach().cpu().numpy()
    outd = '/workspace/Dataset/aggregated_embeddings'
    os.makedirs(outd, exist_ok=True)
    np.save(os.path.join(outd, 'aggregated_embeddingsMoE_Gl_Rl.npy'), aggregated)
    print(f"Aggregated embeddings saved to {outd}/aggregated_embeddings.npy")

# Initialize and run
gamma_values = {n: 1.0 for n in experts.keys()}
router_with_penalties = MoCaERouterWithPenalties(expert_ffns, gamma_values)
process_input_data_with_penalties()
save_aggregated_output_embeddings()

import numpy as np

# Load the aggregated embeddings
def check_aggregated_embeddings_shape(file_path):
    """Load the aggregated embeddings and print their shape."""
    # Load the embeddings from the saved .npy file
    aggregated_embeddings = np.load(file_path, allow_pickle=True).item()

    # Print the shape of each expert's aggregated embedding
    for expert, embedding in aggregated_embeddings.items():
        print(f"Shape of {expert}'s aggregated embedding: {embedding.shape}")

# Path to the saved aggregated embeddings file
aggregated_embeddings_file = '/kaggle/input/worksapce/workspace/orkspace/Dataset/aggregated_embeddings/aggregated_embeddings.npy'

# Check the shape of the aggregated embeddings
check_aggregated_embeddings_shape(aggregated_embeddings_file)

import os
import time
import psutil
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from safetensors.torch import load_file

# --------------------
# Config & Paths
# --------------------
expert_configs = {
    "alpaca": {
        "train_data": "/kaggle/input/worksapce/orkspace/Dataset/Alpaca/Alpaca_Train.json"
    },
    "beavertails": {
        "train_data": "/kaggle/input/worksapce/orkspace/Dataset/BeaverTails/BeaverTails_Train.csv"
    },
    "truthfulqa": {
        "train_data": "/kaggle/input/worksapce/orkspace/Dataset/TruthfulQA/TruthfulQA_Train.csv"
    },

}
EMBEDDINGS_FILE = '/workspace/Dataset/aggregated_embeddings/aggregated_embeddings.npy'

# --------------------
# Label Loader with Safe Fallback
# --------------------
def load_labels(expert_name, label_col='label'):
    path = expert_configs[expert_name]['train_data']
    if path is None:
        raise KeyError(f"No train_data path for {expert_name}")
    df = pd.read_json(path) if path.endswith('.json') else pd.read_csv(path)
    if label_col in df.columns:
        return df[label_col].values
    # Try inferring label column: integer dtype with few unique values
    int_cols = [c for c in df.columns if pd.api.types.is_integer_dtype(df[c])]
    for c in int_cols:
        if df[c].nunique() < len(df) / 2:
            print(f"Info: Using inferred label column '{c}' for {expert_name}")
            return df[c].values
    # No suitable label found
    raise KeyError(f"No label column found for {expert_name} in {path}")

# --------------------
# Calibration & Scoring Metrics
# --------------------

def compute_ece(probs, labels, n_bins=10):
    bins = np.linspace(0,1,n_bins+1)
    confidences = np.max(probs, axis=1)
    preds = np.argmax(probs, axis=1)
    acc = (preds == labels).astype(float)
    ece = 0.0
    for i in range(n_bins):
        mask = (confidences > bins[i]) & (confidences <= bins[i+1])
        if mask.any():
            ece += abs(confidences[mask].mean() - acc[mask].mean()) * mask.sum() / len(labels)
    return ece


def compute_brier(probs, labels):
    N, C = probs.shape
    true_onehot = np.zeros_like(probs)
    true_onehot[np.arange(N), labels] = 1
    return np.mean(np.sum((probs - true_onehot)**2, axis=1))


def temperature_scale(probs, temperature=1.0):
    logits = np.log(np.clip(probs, 1e-12, 1.0)) / temperature
    exp = np.exp(logits)
    return exp / exp.sum(axis=1, keepdims=True)

# --------------------
# Zero-Shot & Few-Shot Evaluation
# --------------------

def eval_zero_shot(embeddings, labels, temp=1.0):
    # Inference timing
    start = time.time()
    logits = torch.tensor(embeddings, dtype=torch.float32)
    probs = torch.softmax(logits, dim=1).numpy()
    infer_time = time.time() - start

    # Metrics
    ece = compute_ece(probs, labels)
    ece_t = compute_ece(temperature_scale(probs, temp), labels)
    brier = compute_brier(probs, labels)

    return {
        'ECE': round(ece,4),
        'ECE-t': round(ece_t,4),
        'Brier': round(brier,4),
        'Inference_Time_s': round(infer_time,4),
        'Train_Time_s': 0.0,
        'Train_Memory_MB': 0.0
    }


def eval_few_shot(embeddings, labels, epochs=5, temp=1.0, device='cpu'):
    X = torch.tensor(embeddings, dtype=torch.float32).to(device)
    y = torch.tensor(labels, dtype=torch.long).to(device)
    num_classes = len(np.unique(labels))
    model = nn.Linear(embeddings.shape[1], num_classes).to(device)
    optimizer = optim.Adam(model.parameters(), lr=1e-3)
    crit = nn.CrossEntropyLoss()

    # Training timing & memory
    t0 = time.time()
    model.train()
    for _ in range(epochs):
        optimizer.zero_grad()
        logits = model(X)
        loss = crit(logits, y)
        loss.backward()
        optimizer.step()
    train_time = time.time() - t0
    train_mem = psutil.Process(os.getpid()).memory_info().rss / 1024**2

    # Inference
    t1 = time.time()
    model.eval()
    with torch.no_grad():
        logits = model(X)
        probs = torch.softmax(logits, dim=1).cpu().numpy()
    infer_time = time.time() - t1

    # Metrics
    ece = compute_ece(probs, labels)
    ece_t = compute_ece(temperature_scale(probs, temp), labels)
    brier = compute_brier(probs, labels)

    return {
        'ECE': round(ece,4),
        'ECE-t': round(ece_t,4),
        'Brier': round(brier,4),
        'Inference_Time_s': round(infer_time,4),
        'Train_Time_s': round(train_time,4),
        'Train_Memory_MB': round(train_mem,4)
    }

# --------------------
# Main Loop
# --------------------

if __name__ == '__main__':
    agg = np.load(EMBEDDINGS_FILE, allow_pickle=True).item()
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    for expert, emb in agg.items():
        print(f"--- {expert.upper()} ---")
        try:
            labels = load_labels(expert)
        except KeyError as e:
            print(f"Skipping '{expert}': {e}")
            continue

        zero = eval_zero_shot(emb, labels)
        few = eval_few_shot(emb, labels, epochs=5, device=device)

        print("Zero-Shot Metrics:")
        for k,v in zero.items(): print(f"  {k}: {v}")
        print("Few-Shot Metrics:")
        for k,v in few.items(): print(f"  {k}: {v}")
        print()